language: r
cache: packages

dist: trusty
sudo: false

warnings_are_errors: true

branches:
  except:
    - gh-pages

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - libhdf5-serial-dev libnetcdf-dev netcdf-bin unzip 

install: true

before_script:
  - bash test/test_setup.sh

script:
  - bash test/test_run_stilt.sh
  - bash test/test_stilt_cli.sh
