language: r
cache: packages

dist: bionic
warnings_are_errors: true

branches:
  except:
    - gh-pages

addons:
  apt:
    packages:
      - libhdf5-serial-dev 
      - libnetcdf-dev
      - netcdf-bin
      - unzip

install:
  - bash test/test_setup.sh

script:
  - bash test/test_run_stilt.sh
  - bash test/test_stilt_cli.sh
