language: r
cache: packages

os: linux
dist: bionic

warnings_are_errors: true

branches:
  except:
    - gh-pages

apt_packages:
  - libhdf5-serial-dev 
  - libnetcdf-dev
  - netcdf-bin
  - unzip

r_packages:
  - dplyr
  - ncdf4
  - parallel
  - raster
  - rslurm

install:
  - bash test/test_setup.sh

script:
  - bash test/test_run_stilt.sh
  - bash test/test_stilt_cli.sh
